// <auto-generated />
using System;
using System.Collections.Generic;
using ForensicGraph.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ForensicGraph.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ForensicGraphDbContext))]
    [Migration("20260912123845_PersonsAndLinks")]
    partial class PersonsAndLinks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.CrimeEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("occurred_at");

                    b.Property<int>("Severity")
                        .HasColumnType("int")
                        .HasColumnName("severity");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasDatabaseName("ix_crime_events_occurred_at");

                    b.HasIndex("Severity")
                        .HasDatabaseName("ix_crime_events_severity");

                    b.ToTable("crime_events", (string)null);
                });

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.EventLink", b =>
                {
                    b.Property<Guid>("FromEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_event_id");

                    b.Property<Guid>("ToEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_event_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("Note")
                        .HasColumnType("text")
                        .HasColumnName("note");

                    b.HasKey("FromEventId", "ToEventId");

                    b.HasIndex("FromEventId")
                        .HasDatabaseName("ix_event_links_from_event_id");

                    b.HasIndex("ToEventId")
                        .HasDatabaseName("ix_event_links_to_event_id");

                    b.ToTable("event_links", (string)null);
                });

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.EventPerson", b =>
                {
                    b.Property<Guid>("CrimeEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("crime_event_id");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("uuid")
                        .HasColumnName("person_id");

                    b.Property<int>("Role")
                        .HasColumnType("int")
                        .HasColumnName("role");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.HasKey("CrimeEventId", "PersonId", "Role");

                    b.HasIndex("CrimeEventId")
                        .HasDatabaseName("ix_event_persons_crime_event_id");

                    b.HasIndex("PersonId")
                        .HasDatabaseName("ix_event_persons_person_id");

                    b.ToTable("event_persons", (string)null);
                });

            modelBuilder.Entity("ForensicGraph.Domain.Persons.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<List<string>>("Citizenships")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("citizenships");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("last_name");

                    b.PrimitiveCollection<List<string>>("PassportNumbers")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("passport_numbers");

                    b.Property<string>("Phone")
                        .HasColumnType("text")
                        .HasColumnName("phone");

                    b.Property<string>("PhysicalDescription")
                        .HasColumnType("text")
                        .HasColumnName("physical_description");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("ix_persons_last_first_name");

                    b.ToTable("persons", (string)null);
                });

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.EventLink", b =>
                {
                    b.HasOne("ForensicGraph.Domain.CrimeEvents.CrimeEvent", null)
                        .WithMany("OutgoingLinks")
                        .HasForeignKey("FromEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.EventPerson", b =>
                {
                    b.HasOne("ForensicGraph.Domain.CrimeEvents.CrimeEvent", null)
                        .WithMany("Persons")
                        .HasForeignKey("CrimeEventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ForensicGraph.Domain.CrimeEvents.CrimeEvent", b =>
                {
                    b.Navigation("OutgoingLinks");

                    b.Navigation("Persons");
                });
#pragma warning restore 612, 618
        }
    }
}
